-- Local bootstrap of the pre-existing remote schema.
--
-- This migration version is already recorded as applied on the remote
-- database, where these tables/functions were created via the dashboard long
-- before migrations existed — so this file's content never executes remotely.
-- It was originally committed empty, which left `supabase db reset` broken
-- locally: later migrations (fantasy town hall) reference public.manager and
-- failed on a fresh local stack.
--
-- The DDL below is reconstructed from db_types.ts (the generated remote
-- types) so that a local stack carries the same tables, composite types, and
-- RPC signatures as production. Function bodies are empty local stubs — the
-- signatures exist so `supabase gen types typescript --local` reproduces the
-- production API surface.
--
-- Every statement is guarded (IF NOT EXISTS / to_regprocedure checks), so the
-- file is idempotent and, in the worst case of ever being replayed against a
-- database that already has the real objects, changes nothing.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.manager (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.season (
  year integer PRIMARY KEY DEFAULT date_part('year', now())::integer,
  created_at timestamptz DEFAULT now(),
  champ integer REFERENCES public.manager(id),
  toilet_bowl_champ integer REFERENCES public.manager(id),
  divisions integer NOT NULL,
  playoff_team_count integer NOT NULL,
  regular_season_weeks integer NOT NULL,
  total_weeks integer,
  teams integer[] NOT NULL
);

CREATE TABLE IF NOT EXISTS public.game (
  created_at timestamptz DEFAULT now(),
  year integer NOT NULL DEFAULT date_part('year', now())::integer,
  week integer NOT NULL,
  home_team integer NOT NULL REFERENCES public.manager(id),
  away_team integer REFERENCES public.manager(id),
  winning_team integer REFERENCES public.manager(id),
  home_score real,
  away_score real,
  home_seed integer,
  away_seed integer,
  is_playoffs boolean NOT NULL,
  is_winners_bracket boolean NOT NULL,
  is_toilet_bowl boolean NOT NULL,
  is_bye_week boolean NOT NULL,
  PRIMARY KEY (year, week, home_team)
);

CREATE TABLE IF NOT EXISTS public.high_point (
  created_at timestamptz DEFAULT now(),
  year integer NOT NULL DEFAULT date_part('year', now())::integer,
  week integer NOT NULL,
  high_point real,
  high_point_manager integer REFERENCES public.manager(id),
  low_point real,
  low_point_manager integer REFERENCES public.manager(id),
  PRIMARY KEY (year, week)
);

CREATE TABLE IF NOT EXISTS public.team (
  created_at timestamptz NOT NULL DEFAULT now(),
  year integer NOT NULL REFERENCES public.season(year),
  manager integer NOT NULL REFERENCES public.manager(id),
  team_name text NOT NULL,
  logo text,
  division integer NOT NULL,
  draft_position integer,
  playoff_seed integer,
  made_playoffs boolean NOT NULL,
  trades integer,
  transactions integer,
  PRIMARY KEY (year, manager)
);

CREATE TABLE IF NOT EXISTS public.albums_of_the_year (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  year integer NOT NULL,
  rank integer NOT NULL,
  album text NOT NULL,
  artist text NOT NULL,
  album_art_url text NOT NULL,
  apple_link text NOT NULL,
  spotify_link text NOT NULL,
  vinyl_link text,
  blurb text
);

CREATE TABLE IF NOT EXISTS public.music_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  title text NOT NULL,
  artist text NOT NULL,
  type text NOT NULL,
  album_art_url text NOT NULL,
  apple_music_url text NOT NULL,
  spotify_url text,
  vinyl_url text,
  blurb text
);

CREATE TABLE IF NOT EXISTS public.top_100_albums (
  id integer PRIMARY KEY,
  album text NOT NULL,
  artist text NOT NULL,
  artwork_url text NOT NULL,
  genre text NOT NULL,
  release_date date NOT NULL,
  tier text NOT NULL,
  apple_music_url text,
  spotify_url text
);

-- ---------------------------------------------------------------------------
-- Enums that already exist remotely in their final shape.
--
-- town_hall_ballot_status is created ('draft','open','closed') by the town
-- hall migration and extended ('upcoming','finished') by the lifecycle
-- migration via ALTER TYPE ADD VALUE. Applied transactionally on a fresh
-- stack, the lifecycle migration would hit Postgres' "unsafe use of new
-- value" restriction (new enum values cannot be used in the transaction that
-- adds them). Creating the full current-remote enum here first makes both
-- later migrations' guards skip cleanly.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  CREATE TYPE public.town_hall_ballot_status AS ENUM (
    'draft',
    'open',
    'closed',
    'upcoming',
    'finished'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

-- ---------------------------------------------------------------------------
-- Composite types backing the fantasy RPCs
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  CREATE TYPE public.all_time_object AS (
    name text,
    is_active boolean,
    total_games integer,
    total_wins integer,
    playoff_games integer,
    playoff_wins integer,
    total_points_for numeric,
    total_points_against numeric,
    high_point_weeks integer,
    low_point_weeks integer,
    transactions integer,
    trades integer,
    championships integer,
    playoff_births integer,
    total_seasons integer
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE public.game_details AS (
    week integer,
    year integer,
    home_score numeric,
    away_score numeric,
    home_manager_name text,
    home_team text,
    home_logo text,
    home_seed integer,
    away_manager_name text,
    away_team text,
    away_logo text,
    away_seed integer,
    is_playoffs boolean,
    is_winners_bracket boolean,
    is_toilet_bowl boolean,
    is_bye_week boolean,
    high_point text,
    low_point text
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE public.head_to_head_object AS (
    name text,
    total_games integer,
    total_wins integer,
    playoff_games integer,
    playoff_wins integer,
    total_points_for numeric,
    total_points_against numeric,
    high_point_weeks integer,
    low_point_weeks integer,
    transactions integer,
    trades integer,
    championships integer,
    playoff_births integer,
    total_seasons integer
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE public.manager_season_object AS (
    year integer,
    total_games integer,
    total_wins integer,
    playoff_games integer,
    playoff_wins integer,
    total_points_for numeric,
    total_points_against numeric,
    high_point_weeks integer,
    low_point_weeks integer,
    logo text,
    playoff_seed integer
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE public.opponents_object AS (
    name text,
    id integer,
    total_games integer,
    total_wins integer
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE public.season_details_object AS (
    manager_name text,
    total_games integer,
    total_wins integer,
    playoff_games integer,
    playoff_wins integer,
    total_points_for numeric,
    total_points_against numeric,
    high_point_weeks integer,
    low_point_weeks integer,
    championships integer
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

-- ---------------------------------------------------------------------------
-- RPC signature stubs (empty result sets locally; real bodies live on remote)
-- Guarded with to_regprocedure so an existing real function is never replaced.
-- ---------------------------------------------------------------------------

DO $do$
BEGIN
  IF to_regprocedure('public.all_time()') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.all_time()
      RETURNS SETOF public.all_time_object
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.head_to_head(integer, integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.head_to_head(team_one integer, team_two integer)
      RETURNS SETOF public.head_to_head_object
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.head_to_head_matchups(integer, integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.head_to_head_matchups(team_one integer, team_two integer)
      RETURNS SETOF public.game_details
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.manager_seasons(integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.manager_seasons(manager_id integer)
      RETURNS SETOF public.manager_season_object
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.opponents(integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.opponents(manager_id integer)
      RETURNS SETOF public.opponents_object
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.season_details(integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.season_details(season_year integer)
      RETURNS SETOF public.season_details_object
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;

  IF to_regprocedure('public.week_matchups(integer, integer)') IS NULL THEN
    EXECUTE $sql$
      CREATE FUNCTION public.week_matchups(season_year integer, selected_week integer)
      RETURNS SETOF public.game_details
      LANGUAGE plpgsql STABLE
      AS $fn$ BEGIN RETURN; END; $fn$
    $sql$;
  END IF;
END
$do$;
